"""Add invoice payments

Revision ID: 5a7fb81313ea
Revises: 
Create Date: 2026-08-15 15:36:12.265085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7fb81313ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('issue_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Balance', sa.Float(), nullable=False))
        batch_op.alter_column('tax_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.create_unique_constraint(None, ['invoice_number'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('tax_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('Balance')
        batch_op.drop_column('amount')
        batch_op.drop_column('due_date')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
