"""Update supplier payment references

Revision ID: c7927e6063bb
Revises: REPLACE_WITH_GENERATED_REVISION
Create Date: 2026-09-03 17:09:29.082785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7927e6063bb'
down_revision = 'REPLACE_WITH_GENERATED_REVISION'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_reference', sa.String(length=120), nullable=True))
        batch_op.alter_column('payment_reference',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('receipt_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['payment_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('receipt_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('payment_reference',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('external_reference')

    # ### end Alembic commands ###
